import os
import pandas as pd
import joblib

# Load models into memory once at startup
MODEL_PATH = 'precast_multi_model.pkl'
FEATURES_PATH = 'model_features.pkl'

if os.path.exists(MODEL_PATH) and os.path.exists(FEATURES_PATH):
    _model = joblib.load(MODEL_PATH)
    _features = joblib.load(FEATURES_PATH)
else:
    raise FileNotFoundError("Model or features PKL files not found. Ensure they exist for production!")

def get_prediction(input_data):
    df_in = pd.DataFrame([input_data])
    df_in = df_in[_features]
    
    preds = _model.predict(df_in)[0]

    return {
        'Strength gain rate': round(preds[0], 2),
        'Demould time': round(preds[1], 1),
        'Cost per element': round(preds[2], 0),
        'Energy consumption': round(preds[3], 0),
        'Mold utilization': round(preds[4], 1),
        'Risk of under-strength': round(preds[5], 2)
    }

if __name__ == "__main__":
    print("\n--- TEST PREDICTION LOGIC ---")
    test_input = {
        'Cement content': 400,
        'W/C ratio': 0.42,
        'SCM %': 25,
        'Ramp rate': 20,
        'Hold temperature': 65,
        'Ambient temperature': 32,
        'Maturity index': 550,
        'Mold availability': 85,
        'Energy tariff': 7
    }
    result = get_prediction(test_input)
    print("Inputs:")
    for k, v in test_input.items():
        print(f"  {k}: {v}")
    print("\nOutputs Generated by Multi-Output XGBoost:")
    for k, v in result.items():
        print(f"  {k}: {v}")
